### ISSUE TITLE
Use absolute process virtual address for Base (not relative to module base)

### ISSUE THREAD

**Issue by VelocityRa** [kugelrund/LiveSplit.MemoryGraph#34]
When making https://github.com/kugelrund/LiveSplit.MemoryGraph/pull/33 I run into an issue where MemoryGraph was not fetching the correct address (process virtual address) for the "Base" that you see the value in, in for example Cheat Engine.

So I suspected that it was operating in a different address space. I found pcsx2.exe's module base address in x32dbg.exe, subtracted it from the field's address (the one in process address space, that you'd see in ie. CE) and called it a day.

However, it doesn't work for other people. The pcsx2.exe module is not loaded in the same address for everyone.

Maybe doing something wrong - and there is _some_ way of operating in absolute process virtual address space?

Then again, I don't see any other emulated games in the xml. So maybe it's first time this has been necessary?
(since for an emulator, we're almost never interested in _relative_ addresses from the module base)

---
**edit**: just for reference:
Process Virtual Address: `0x20262E10` (that you see in CE)
pcsx2.exe module base (only for me): `0x80000`
Final "Base" value I ended up with for the PR: `0x20262E10` - `0x80000` = `0x201E2E10`

**Comment by kugelrund** [comment]
Hm does it work if you leave the module empty? Normally you should leave it empty if the offset is just based on the main process.

**Comment by VelocityRa** [comment]
Nope, leaving it empty is what I tried first, doesn't work, iirc it defaults to offsetting from the main module.

**Comment by VelocityRa** [comment]
I guess it makes sense for it to be the default since most games this is used for aren't emulated, but an _option_ for absolute bases for such use cases (emulators) would be cool to see.

**Comment by kugelrund** [comment]
Ah ok starting to understand. Still not quite sure how an absolute base would help, wouldn't this be different for every user as well? We just use LiveSplit's `DeepPointer`, so exactly what you have in ASL scripts for autosplitting. How do you work with that, or is there no such splitter for the game on emulator?

**Comment by VelocityRa** [comment]
This would not be different for every user, no. PCSX2 allocates the emulated RAM area at a fixed virtual address.

**Comment by VelocityRa** [comment]
Seems `DeepPointer` [doesn't offer the ability to work with absolute addresses](https://github.com/LiveSplit/LiveSplit/blob/master/LiveSplit/LiveSplit.Core/ComponentUtil/DeepPointer.cs#L91), so if you want to keep using that you'd have to get the process module's main module offset/base and subtract it yourself.

This would only be necessary for the Base btw, not the offsets.

**Comment by kugelrund** [comment]
Idk, i think there very much is support for absolute addresses if you use a [certain constructor](https://github.com/LiveSplit/LiveSplit/blob/master/LiveSplit/LiveSplit.Core/ComponentUtil/DeepPointer.cs#L33). Just think ASL does not use allow to use it, but with a Component like this you can. Implemented it like that when module is set to `[absolute_base]`. Already adapted for your game in the XML, please check if it works like this.

**Comment by VelocityRa** [comment]
Ah I somehow missed that :)
Could you share a built .dll? I don't have a dev env set up.
And maybe if it works make a new Release on Github.

**Comment by SuiMachine** [comment]
It's already in https://github.com/kugelrund/LiveSplit.MemoryGraph/commit/b810c0791c8c022366e29c072ad795f71a333e7c and as far as I can see @kugelrund already pushed it in main branch so it should autoupdate on LiveSplit launch.

**Comment by kugelrund** [comment]
Yeah what Sui said, alternatively the DLL is in the `Components` subdirectory

**Comment by VelocityRa** [comment]
Ahh cool.

Works perfectly, thanks. :)
